default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  username: <%= ENV['DB_USER'] %>
  database: <%= ENV['DB_NAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database: app_production
  username: app
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
