version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passowrd
      MYSQL_USER: http-only-cookie 
      MYSQL_DATABASE: http-only-cookie-db
      MYSQL_PASSWORD: http-only-cookie-password
    volumes:
      - ./backend/tmp/db:/var/lib/mysql
    ports:
      - 3306:3306
  backend:
    build: ./backend
    stdin_open: true
    tty: true
    environment:
      DB_USER: http-only-cookie
      DB_NAME: http-only-cookie-db
      DB_PASSWORD: http-only-cookie-password
      DB_HOST: db
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - 3001:3001
    volumes:
      - ./frontend:/usr/src/app
      - ./frontend/node_modules:/usr/src/app/node_modules
